---
label: Project
name: project
fields:
- type: text
  name: title
  label: Título
  config:
    required: true
- type: text
  name: company
  label: Empresa
  config:
    required: true
- type: number
  name: year
  label: Ano
  config:
    required: true
- type: text
  name: role
  label: Cargo
  config:
    required: true
- type: text
  name: duration
  label: Duração
  config:
    required: true
- type: tag-list
  name: categories
  label: Categorias
- type: file
  name: cover
  label: Capa
  config:
    required: true
- type: textarea
  name: summary
  label: Resumo
  config:
    required: true
    rows: 3
- type: boolean
  name: featured
  label: Destaque?
  default: false
- type: number
  name: order
  label: Ordem
  default: 99
- type: rich-text
  name: body
  label: Conteúdo
  isBody: true
